import http from 'node:http';
import { URL } from 'node:url';
import { createRemoteJWKSet, jwtVerify } from 'jose';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/streamableHttp.js';
import { z } from 'zod';

const SB_URL = process.env.RAVI_SUPABASE_URL;
const SB_KEY = process.env.RAVI_SUPABASE_SERVICE_ROLE_KEY;
const PORT = Number(process.env.PORT || 3000);
const ISSUER = (process.env.OAUTH_ISSUER || '').replace(/\/$/, '');
const AUDIENCE = process.env.OAUTH_AUDIENCE || '';
const RESOURCE = process.env.MCP_RESOURCE_URL || `http://localhost:${PORT}/mcp`;
const SCOPE = process.env.OAUTH_REQUIRED_SCOPE || 'ravi_traders:read';
if (!SB_URL || !SB_KEY || !ISSUER || !AUDIENCE) process.exit(1);
const jwks = createRemoteJWKSet(new URL(`${ISSUER}/.well-known/jwks.json`));
const base = SB_URL.replace(/\/$/,'') + '/rest/v1/';
const money = n => Math.round(Number(n||0)*100)/100;
const out = x => ({content:[{type:'text',text:JSON.stringify(x,null,2)}]});
async function sb(path){const r=await fetch(base+path,{headers:{apikey:SB_KEY,Authorization:`Bearer ${SB_KEY}`,'Content-Type':'application/json'}});const t=await r.text();let d;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw Error(`Supabase ${r.status}: ${typeof d==='string'?d:JSON.stringify(d)}`);return d}
async function auth(req){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return null;try{const {payload}=await jwtVerify(h.slice(7),jwks,{issuer:ISSUER,audience:AUDIENCE});const scopes=String(payload.scope||payload.scp||'').split(/\s+/);return scopes.includes(SCOPE)?payload:null}catch{return null}}
function metadata(){return {resource:RESOURCE,authorization_servers:[ISSUER],scopes_supported:[SCOPE],bearer_methods_supported:['header']}}
function tools(s){
 s.registerTool('search_customers',{description:'Search customers by name, phone, email or code. Read-only.',inputSchema:{query:z.string(),limit:z.number().int().min(1).max(50).default(10)}},async({query,limit})=>out({customers:await sb(`customers?or=(name.ilike.*${encodeURIComponent(query)}*,phone.ilike.*${encodeURIComponent(query)}*,email.ilike.*${encodeURIComponent(query)}*,customer_code.ilike.*${encodeURIComponent(query)}*)&select=id,customer_code,name,phone,alternate_phone,email,address,gstin,category,credit_limit,discount_percent,status&order=name&limit=${limit}`)}));
 s.registerTool('get_customer_balance',{description:'Get customer invoices, paid and outstanding. Read-only.',inputSchema:{customer_id:z.string().uuid().optional(),customer_name:z.string().optional()}},async({customer_id,customer_name})=>{let c=customer_id?await sb(`customers?id=eq.${encodeURIComponent(customer_id)}&select=*`):await sb(`customers?name.ilike.*${encodeURIComponent(customer_name||'')}*&select=*&limit=10`);if(!c.length)throw Error('Customer not found');const results=[];for(const x of c){const inv=await sb(`invoices?customer_id=eq.${x.id}&select=id,invoice_no,invoice_date,due_date,total,status&order=invoice_date.desc`);const ids=inv.map(i=>i.id);const p=ids.length?await sb(`payments?invoice_id=in.(${ids.join(',')})&select=invoice_id,amount`):[];const pb={};for(const a of p)pb[a.invoice_id]=money((pb[a.invoice_id]||0)+Number(a.amount||0));const rows=inv.map(i=>({...i,paid_amount:pb[i.id]||0,outstanding_amount:money(Number(i.total||0)-(pb[i.id]||0))}));results.push({customer:x,total_invoiced:money(rows.reduce((a,i)=>a+Number(i.total||0),0)),total_paid:money(rows.reduce((a,i)=>a+Number(i.paid_amount||0),0)),outstanding:money(rows.reduce((a,i)=>a+Number(i.outstanding_amount||0),0)),invoices:rows})}return out({results})});
 s.registerTool('search_invoices',{description:'Search invoices by number or customer. Read-only.',inputSchema:{query:z.string(),limit:z.number().int().min(1).max(100).default(20)}},async({query,limit})=>out({invoices:await sb(`invoices?or=(invoice_no.ilike.*${encodeURIComponent(query)}*,customer_name_snapshot.ilike.*${encodeURIComponent(query)}*)&select=id,invoice_no,customer_id,customer_name_snapshot,invoice_date,due_date,total,subtotal,tax_percent,tax_amount,status,notes,created_at&order=created_at.desc&limit=${limit}`)}));
 s.registerTool('get_invoice',{description:'Get invoice, items and payment history. Read-only.',inputSchema:{invoice_no:z.string()}},async({invoice_no})=>{const a=await sb(`invoices?invoice_no=eq.${encodeURIComponent(invoice_no)}&select=*`);if(!a.length)throw Error('Invoice not found');const i=a[0],items=await sb(`invoice_items?invoice_id=eq.${i.id}&select=*`),payments=await sb(`payments?invoice_id=eq.${i.id}&select=*`),paid=money(payments.reduce((x,p)=>x+Number(p.amount||0),0));return out({invoice:i,items,payments,paid_amount:paid,outstanding_amount:money(Number(i.total||0)-paid)})});
 s.registerTool('list_products',{description:'List product catalog and rates. Read-only.',inputSchema:{query:z.string().optional(),limit:z.number().int().min(1).max(100).default(50)}},async({query,limit})=>out({products:await sb(query?`products?name.ilike.*${encodeURIComponent(query)}*&select=id,company_id,name,unit,rate,updated_at&order=name&limit=${limit}`:`products?select=id,company_id,name,unit,rate,updated_at&order=name&limit=${limit}`)}));
 s.registerTool('sales_summary',{description:'Sales summary for a date range. Read-only.',inputSchema:{start_date:z.string(),end_date:z.string()}},async({start_date,end_date})=>{const i=await sb(`invoices?invoice_date=gte.${start_date}&invoice_date=lte.${end_date}&select=id,total`);const ids=i.map(x=>x.id);const p=ids.length?await sb(`payments?invoice_id=in.(${ids.join(',')})&select=amount`):[];const ti=money(i.reduce((a,x)=>a+Number(x.total||0),0)),tp=money(p.reduce((a,x)=>a+Number(x.amount||0),0));return out({start_date,end_date,invoice_count:i.length,total_invoiced:ti,total_paid:tp,outstanding:money(ti-tp)})});
 s.registerTool('get_customer_invoices',{description:'Get customer invoice history. Read-only.',inputSchema:{customer_id:z.string().uuid().optional(),customer_name:z.string().optional(),limit:z.number().int().min(1).max(100).default(50)}},async({customer_id,customer_name,limit})=>{let id=customer_id;if(!id){const a=await sb(`customers?name.ilike.*${encodeURIComponent(customer_name||'')}*&select=id,name,phone,email,address&limit=10`);if(!a.length)throw Error('Customer not found');id=a[0].id}return out({invoices:await sb(`invoices?customer_id=eq.${id}&select=id,invoice_no,invoice_date,due_date,total,status,notes&order=invoice_date.desc&limit=${limit}`)})});
 s.registerTool('get_overdue_invoices',{description:'Find overdue invoices with positive balance. Read-only.',inputSchema:{as_of:z.string().optional(),limit:z.number().int().min(1).max(100).default(50)}},async({as_of,limit})=>{const d=as_of||new Date().toISOString().slice(0,10),i=await sb(`invoices?due_date=lt.${d}&select=id,invoice_no,customer_id,customer_name_snapshot,invoice_date,due_date,total,status&order=due_date.asc&limit=${limit}`),ids=i.map(x=>x.id),p=ids.length?await sb(`payments?invoice_id=in.(${ids.join(',')})&select=invoice_id,amount`):[],pb={};for(const x of p)pb[x.invoice_id]=money((pb[x.invoice_id]||0)+Number(x.amount||0));return out({as_of:d,invoices:i.filter(x=>!['PAID','CANCELLED','VOID'].includes(String(x.status||'').toUpperCase())).map(x=>({...x,paid_amount:pb[x.id]||0,outstanding_amount:money(Number(x.total||0)-(pb[x.id]||0))})).filter(x=>x.outstanding_amount>0)})});
 s.registerTool('get_product_details',{description:'Find product details and current rate. Read-only.',inputSchema:{query:z.string(),limit:z.number().int().min(1).max(50).default(20)}},async({query,limit})=>out({products:await sb(`products?name.ilike.*${encodeURIComponent(query)}*&select=id,company_id,name,unit,rate,updated_at&order=name&limit=${limit}`)}));
 s.registerTool('sales_by_product',{description:'Summarize invoice items by product for a date range. Read-only.',inputSchema:{start_date:z.string(),end_date:z.string(),query:z.string().optional()}},async({start_date,end_date,query})=>{const i=await sb(`invoices?invoice_date=gte.${start_date}&invoice_date=lte.${end_date}&select=id`),ids=i.map(x=>x.id);if(!ids.length)return out({products:[]});const items=await sb(`invoice_items?invoice_id=in.(${ids.join(',')})&select=description,qty,unit,rate,amount`),m={};for(const x of items){const n=String(x.description||'Unknown').trim();if(query&&!n.toLowerCase().includes(query.toLowerCase()))continue;m[n]??={description:n,unit:x.unit||null,quantity:0,sales_value:0};m[n].quantity+=Number(x.qty||0);m[n].sales_value=money(m[n].sales_value+Number(x.amount||Number(x.qty||0)*Number(x.rate||0)))}return out({start_date,end_date,products:Object.values(m).sort((a,b)=>b.sales_value-a.sales_value)})});
 s.registerTool('invoice_aging',{description:'Outstanding invoice aging buckets. Read-only.',inputSchema:{as_of:z.string().optional()}},async({as_of})=>{const d=as_of||new Date().toISOString().slice(0,10),i=await sb('invoices?select=id,due_date,total,status&due_date=not.is.null'),ids=i.map(x=>x.id),p=ids.length?await sb(`payments?invoice_id=in.(${ids.join(',')})&select=invoice_id,amount`):[],pb={};for(const x of p)pb[x.invoice_id]=money((pb[x.invoice_id]||0)+Number(x.amount||0));const b={current:0,'1_30':0,'31_60':0,'61_90':0,'90_plus':0};for(const x of i){const bal=money(Number(x.total||0)-(pb[x.id]||0));if(bal<=0)continue;const days=Math.floor((new Date(d)-new Date(x.due_date))/86400000);const k=days<=0?'current':days<=30?'1_30':days<=60?'31_60':days<=90?'61_90':'90_plus';b[k]=money(b[k]+bal)}return out({as_of:d,buckets:b})});
 s.registerTool('get_company_catalog',{description:'List companies/brands. Read-only.',inputSchema:{query:z.string().optional(),limit:z.number().int().min(1).max(100).default(100)}},async({query,limit})=>out({companies:await sb(query?`companies?name.ilike.*${encodeURIComponent(query)}*&select=id,name,material_type,created_at&order=name&limit=${limit}`:`companies?select=id,name,material_type,created_at&order=name&limit=${limit}`)}));
 s.registerTool('get_customer_sales',{description:'Summarize sales by customer for a date range. Read-only.',inputSchema:{start_date:z.string(),end_date:z.string()}},async({start_date,end_date})=>{const i=await sb(`invoices?invoice_date=gte.${start_date}&invoice_date=lte.${end_date}&select=customer_id,customer_name_snapshot,total`),m={};for(const x of i){const k=x.customer_id||x.customer_name_snapshot||'Unknown';m[k]??={customer_id:x.customer_id,customer_name:x.customer_name_snapshot,invoiced:0,invoice_count:0};m[k].invoiced=money(m[k].invoiced+Number(x.total||0));m[k].invoice_count++}return out({customers:Object.values(m).sort((a,b)=>b.invoiced-a.invoiced)})});
 s.registerTool('recent_invoices',{description:'Get recent invoices. Read-only.',inputSchema:{limit:z.number().int().min(1).max(100).default(20)}},async({limit})=>out({invoices:await sb(`invoices?select=id,invoice_no,customer_id,customer_name_snapshot,invoice_date,due_date,total,status,created_at&order=created_at.desc&limit=${limit}`)}));
 s.registerTool('invoice_status_summary',{description:'Invoice count and value by status. Read-only.',inputSchema:{start_date:z.string().optional(),end_date:z.string().optional()}},async({start_date,end_date})=>{let q='invoices?select=status,total';if(start_date&&end_date)q+=`&invoice_date=gte.${start_date}&invoice_date=lte.${end_date}`;const rows=await sb(q),m={};for(const x of rows){const k=x.status||'UNKNOWN';m[k]??={status:k,count:0,total:0};m[k].count++;m[k].total=money(m[k].total+Number(x.total||0))}return out({summary:Object.values(m)})});
 s.registerTool('get_payment_history',{description:'Read payment history for invoice or customer. Read-only.',inputSchema:{invoice_id:z.string().uuid().optional(),customer_id:z.string().uuid().optional(),limit:z.number().int().min(1).max(100).default(100)}},async({invoice_id,customer_id,limit})=>{if(!invoice_id&&!customer_id)throw Error('Provide invoice_id or customer_id');let q=`payments?select=id,invoice_id,customer_id,amount,payment_date,method,notes,note,razorpay_payment_id,created_at&order=created_at.desc&limit=${limit}`;if(invoice_id)q+=`&invoice_id=eq.${invoice_id}`;if(customer_id)q+=`&customer_id=eq.${customer_id}`;return out({payments:await sb(q)})});
}
function server(){const s=new McpServer({name:'ravi-traders-mcp',version:'4.0.0'});tools(s);return s}
function challenge(res){res.writeHead(401,{'Content-Type':'application/json','WWW-Authenticate':`Bearer resource_metadata="${RESOURCE.replace(/\/mcp$/,'')}/.well-known/oauth-protected-resource/mcp"`,'Cache-Control':'no-store'});res.end(JSON.stringify({error:'unauthorized',message:'OAuth access token required'}))}
const h=http.createServer(async(req,res)=>{try{const u=new URL(req.url,`http://${req.headers.host}`);if(u.pathname==='/health'&&req.method==='GET'){res.writeHead(200,{'Content-Type':'application/json'});return res.end(JSON.stringify({ok:true,service:'ravi-traders-mcp',transport:'streamable-http',tools:16,version:'4.0.0',oauth:true}))}if(u.pathname.startsWith('/.well-known/oauth-protected-resource')&&req.method==='GET'){res.writeHead(200,{'Content-Type':'application/json','Cache-Control':'public,max-age=300'});return res.end(JSON.stringify(metadata()))}if(u.pathname==='/mcp'){if(!['GET','POST','DELETE'].includes(req.method)){res.writeHead(405,{Allow:'GET, POST, DELETE'});return res.end()}if(!(await auth(req)))return challenge(res);const chunks=[];for await(const c of req)chunks.push(c);const raw=Buffer.concat(chunks).toString();const body=raw?JSON.parse(raw):undefined;const t=new StreamableHTTPServerTransport({sessionIdGenerator:undefined,enableJsonResponse:true});const s=server();await s.connect(t);return await t.handleRequest(req,res,body)}res.writeHead(404,{'Content-Type':'application/json'});res.end(JSON.stringify({error:'Not Found'}))}catch(e){console.error(e);if(!res.headersSent){res.writeHead(500,{'Content-Type':'application/json'});res.end(JSON.stringify({error:'Internal Server Error'}))}}});
h.listen(PORT,'0.0.0.0',()=>console.log(`Ravi Traders MCP V4 listening on ${PORT}`));
